services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    networks:
      - zekrypt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    networks:
      - zekrypt-network

networks:
  zekrypt-network:
