services:

  backend:
    build:
      target: production

    container_name: zekrypt-backend-prod

    ports:
      - "8080:8080"

    env_file:
      - .env.prod

    restart: unless-stopped

  frontend:
    build:
      target: production

    container_name: zekrypt-frontend-prod

    ports:
      - "3000:3000"

    env_file:
      - .env.prod

    restart: unless-stopped

  postgres:
    container_name: zekrypt-postgres-prod

    environment:
      POSTGRES_DB: zekrypt_prod_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    container_name: zekrypt-redis-prod

    command: redis-server --appendonly yes

    volumes:
      - redis-prod-data:/data

    restart: unless-stopped

volumes:
  postgres-prod-data:
  redis-prod-data:
  